### PR TITLE
Fix unit test coverage

### PR DESCRIPTION
**Pull request by bhllau**
Fix https://github.com/storyprotocol/typescript-sdk/issues/34

### CODE REVIEW

**Comment by edisonz0718** [comment]
Could you check why didn't it trigger CI?

**Comment by bhllau** [comment]
The CI has come back. I have not done any changes.

**Review by DonFungible — APPROVED** [review]

**Review by edisonz0718 — CHANGES_REQUESTED** [review]
We need to make sure we exclude all the interfaces from test coverage. If there is no clean way to do that, we can waive this task for now but focus on getting the test coverage check in CI first.

**Comment by bhllau** [comment]
@edisonz0718 : I tried adding the `--exclude './src/interfaces` flag to c8, according to the c8's documentation, but the flag does not seem to take effect automatically. I may need more time to experiment how to do it.

**Comment by bhllau** [comment]
What I read is that pre-compiling the TS files will provide the source map to c8 to enable the exclude flag. Currently, tsc is bound to the npm start script . I think it will take a bit of time to experiment pre-compiling the scripts and have it in-sync with the current start script.

**Comment by bhllau** [comment]
@edisonz0718 : Can we still merge this to dev first please? I have created a separate issue here https://github.com/storyprotocol/typescript-sdk/issues/34 so we can come back to this later.

**Comment by edisonz0718** [comment]
> @edisonz0718 : Can we still merge this to dev first please? I have created a separate issue here #34 so we can come back to this later.

The test coverage doesn't look good. A lot of zero-coverage files. 
Also, I think it's not a good idea to exclude a specific folder from the test coverage report. What if later on there are files that contain both the interface and non-interface code? It would be better if we could exclude interfaces from the check instead of excluding the folders. 

We don't have to complete this now. Let's come back to this later.

**Comment by edisonz0718** [comment]
The task has been done in #73

**Pull request closed without merging**
