### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by bhllau**
PR to resolve storyprotocol/typescript-sdk#17.

### CODE REVIEW

**Comment by bhllau** [comment]
Currently, `pnpm fix` is breaking.

**Comment by bhllau** [comment]
Turbo CI working after updating node and pnpm version in workflow action descriptions.

**Comment by bhllau** [comment]
Just keeping Docker CI as reference. I can remove it later if it is too difficult to maintain.

**Review by edisonz0718 — COMMENTED** [review]
I think we should return the docker-ci off. Otherwise I assume every PR needs to run 2 CI workflows. It consumes more Github running minutes. If we want to keep the code for reference, is there a way to disable the run?

**Comment by bhllau** [comment]
We can remove it. I will just put it in a separate branch.

**Review by edisonz0718 — APPROVED** [review]

**Pull request merged**
