### PR TITLE
Feat/issue #117 contracts ci workflow

### PR DESCRIPTION
**Pull request by baxterjfinch**
Issue #117

### CODE REVIEW

**Comment by baxterjfinch** [comment]
I'd like to get feedback on the approach here - this requires adding hardhat into the project dependencies which is rather bloated. 

We can look into a slimmer abi generator like [0x/abi-gen](https://www.npmjs.com/package/@0x/abi-gen) or similar.

Let me know if pulling this locally and running `make compile_contracts` works as expected.

**Review by edisonz0718 — CHANGES_REQUESTED** [review]
I think we need to trim down the artifacts folder. We should only pull the files and functions we need. Otherwise it increase our package size

**Comment by baxterjfinch** [comment]
> I think we need to trim down the artifacts folder. We should only pull the files and functions we need. Otherwise it increase our package size

This is complete - lmk if there's anything else!

**Comment by edisonz0718** [comment]
> > I think we need to trim down the artifacts folder. We should only pull the files and functions we need. Otherwise it increase our package size
> 
> This is complete - lmk if there's anything else!

What do you think about changing the folder name 'artifacts' to 'json' or something else that is more representative to this folder? artifacts for me seem to mean something else

**Comment by baxterjfinch** [comment]
> > > I think we need to trim down the artifacts folder. We should only pull the files and functions we need. Otherwise it increase our package size
> > 
> > 
> > This is complete - lmk if there's anything else!
> 
> What do you think about changing the folder name 'artifacts' to 'json' or something else that is more representative to this folder? artifacts for me seem to mean something else

That makes sense to me - Done!

**Review by edisonz0718 — APPROVED** [review]
LGTM just wonder why is the pnpm lock file changed

**Pull request merged**
